#!/bin/bash

echo This is a script that gives instructions on how to update names for this template project.
echo This is a script to remove a small bit of friction from adding stuff that does the updating automatically later.

echo First thing it is probably a good idea to confirm that the template builds and runs properly without any modifications.


echo The "rename-me" folder should be renamed to the name of your new project that uses the template.
echo "(We'll keeping referring to that folder with the name \"rename-me\")"
echo The following files contain references to "rename-me" that should be updated.
echo '* ./Cargo.toml'
echo '* ./README.md'
echo '* ./rename-me/Cargo.toml'
echo '  * This also contains authorship information that may need updating.'
echo '* ./libs/platform/src/platform.rs'
echo '* ./static/index.html'
echo '* ./.project.gf'
echo '  * This is only needed if you plan to debug with rust-gdb via gf. Otherwise both ./.project.gf and ./rust-gdb can be deleted'


echo "After swapping out \"rename-me\" for your chosen name, building with the updated instuctions should work."

echo 'You might also want to confirm that the license dates are up to date. And if you reading this are not Ryan Wiedemann, you will probably want to update the name(s) on the licenses.'